### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by sateffen** [IonicaBizau/emoji-names#3]
Just a little hint: You're code doesn't work at all, and the reason is simple: You can't reassign to a constant after definition.

You're defining `emojis` as `const` while requiring it, but 3 lines later you try to reassign `null` to it, which is invalid.

Simply use `let`, and everything is fine.

**Comment by IonicaBizau** [comment]
@sateffen Thanks for heads-up! I remember fixing a similar issue in another package. Probably this worked in older versions of node. 😁 

Should be fixed now! Cheers! 😄
